spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 8002
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      healthcheck:
      enabled: true
      lease:
      duration: 5
  instance:
    preferIpAddress: true
    
 